apiVersion: v1
kind: Service
metadata:
  name: goserver-service-loadbalancer
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
  - name: goserver-service
    port: 8081
    targetPort: 8000
    protocol: TCP

    