apiVersion: v1
kind: Service
metadata:
  name: goserver-service-nodeport
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
  - name: goserver-service
    port: 8001
    targetPort: 80
    protocol: TCP
    nodePort: 30001

    